# Generated by Django 4.2.2 on 2023-10-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_image',
            field=models.ImageField(default='default.jpeg', upload_to='item_photos'),
        ),
    ]
